# Generated by Django 5.2.6 on 2025-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmanagement',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
