# Generated by Django 5.2.6 on 2025-10-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0002_alter_riskmanagement_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationinvitation',
            old_name='organization',
            new_name='organization_name',
        ),
    ]
