class InitiativePlanningChoicesService:
    """
    Enterprise-grade initiative_planning hierarchy:
    Strategic Pillars -> Areas
    Two levels only, no initiative_planning names, no empty lists
    """

    INITIATIVE_HIERARCHY = {
        "Financial Excellence": [
            "Revenue Growth",
            "Cost Optimization",
            "Investment Strategy",
            "Capital Allocation",
            "Financial Planning & Analysis",
            "Treasury & Cash Management",
            "Mergers & Acquisitions",
            "Risk & Compliance",
            "Financial Controls",
            "Operational Efficiency",
            "Pricing Strategy",
            "Profitability Analysis",
            "Working Capital Management",
            "Debt & Capital Management",
            "Shareholder Relations",
            "Revenue Diversification",
            "Financial Forecasting",
            "Expense Management",
            "Tax Optimization",
            "Regulatory Reporting",
            "Internal Audit",
            "Insurance & Risk Transfer",
            "Investment Portfolio Management",
            "Cost Reduction Programs",
            "Performance Metrics & KPIs",
            "Others",

        ],
        "Customer Excellence": [
            "Customer Acquisition",
            "Customer Retention",
            "Customer Satisfaction",
            "Customer Experience Design",
            "Customer Insights & Analytics",
            "Market Segmentation",
            "Customer Loyalty Programs",
            "Digital Marketing",
            "Brand Management",
            "Sales Enablement",
            "Channel Management",
            "Customer Support",
            "Complaint Resolution",
            "Customer Communication",
            "Omnichannel Strategy",
            "Customer Journey Mapping",
            "Customer Feedback Systems",
            "Personalization & CRM",
            "Upsell & Cross-sell Strategy",
            "Customer Advocacy",
            "Customer Data Platform",
            "Net Promoter Score",
            "Market Research",
            "Social Media Engagement",
            "Customer Segmentation",
            "Others",

        ],
        "Operational Excellence": [
            "Process Optimization",
            "Supply Chain Management",
            "Logistics & Distribution",
            "Inventory Management",
            "Production Planning",
            "Quality Assurance",
            "Operational Metrics",
            "Lean & Six Sigma",
            "Performance Dashboards",
            "Workflow Automation",
            "Continuous Improvement",
            "Vendor Management",
            "Facility Management",
            "Maintenance & Reliability",
            "Procurement",
            "Capacity Planning",
            "Standard Operating Procedures",
            "Cost Efficiency",
            "Technology Enablement",
            "Digital Transformation",
            "Risk Management",
            "Business Continuity",
            "Compliance & Audit",
            "Resource Utilization",
            "Operational Strategy",
            "Others",

        ],
        "Innovation & Growth": [
            "Product Innovation",
            "Service Innovation",
            "R&D Management",
            "Design Thinking",
            "Prototyping & MVP",
            "Market Expansion",
            "Emerging Technologies",
            "Intellectual Property",
            "Innovation Labs",
            "Cross-functional Teams",
            "Customer Co-creation",
            "Agile Product Development",
            "Digital Solutions",
            "Process Innovation",
            "Idea Management",
            "Technology Scouting",
            "Product Portfolio Management",
            "Open Innovation",
            "Sustainability Innovation",
            "Innovation Metrics",
            "Global R&D Collaboration",
            "Innovation Culture",
            "Startup Partnerships",
            "Strategic Alliances",
            "Innovation Training",
            "Others",

        ],
        "Human Capital Excellence": [
            "Talent Acquisition",
            "Talent Development",
            "Leadership Development",
            "Performance Management",
            "Succession Planning",
            "Employee Engagement",
            "Organizational Culture",
            "Workforce Planning",
            "Employee Retention",
            "Learning & Development",
            "Competency Frameworks",
            "Diversity & Inclusion",
            "Employee Wellbeing",
            "Internal Communication",
            "Coaching & Mentoring",
            "Team Collaboration",
            "Recognition & Rewards",
            "Career Pathing",
            "Internal Mobility",
            "Change Management",
            "HR Technology",
            "Employee Surveys",
            "Remote Work Enablement",
            "Talent Analytics",
            "HR Compliance",
            "Others",

        ],
        "Digital Transformation": [
            "Cloud Strategy",
            "Cybersecurity",
            "Data Analytics",
            "Automation",
            "Digital Workplace",
            "IoT Enablement",
            "IT Infrastructure",
            "Enterprise Architecture",
            "Software Development",
            "Mobile Solutions",
            "AI & Machine Learning",
            "Business Intelligence",
            "CRM Systems",
            "ERP Systems",
            "IT Governance",
            "Digital Innovation",
            "Process Digitization",
            "DevOps & Agile",
            "IT Cost Optimization",
            "Integration & APIs",
            "Technology Roadmap",
            "Data Governance",
            "Cloud Adoption",
            "Collaboration Tools",
            "IT Risk Management",
            "Others",

        ],
        "Sales & Marketing": [
            "Sales Strategy",
            "Sales Operations",
            "Account Management",
            "Channel Strategy",
            "Lead Generation",
            "Marketing Campaigns",
            "Brand Strategy",
            "Digital Marketing",
            "Content Marketing",
            "Pricing Strategy",
            "Market Intelligence",
            "Customer Segmentation",
            "CRM Optimization",
            "Promotions & Incentives",
            "Event Marketing",
            "Product Marketing",
            "Sales Enablement",
            "Customer Acquisition",
            "Loyalty Programs",
            "Upselling & Cross-selling",
            "Competitive Analysis",
            "Referral Programs",
            "Sales Training",
            "Advertising Strategy",
            "Customer Retention",
            "Others",

        ],
        "Risk & Compliance": [
            "Regulatory Compliance",
            "Internal Audit",
            "Cybersecurity Risk",
            "Operational Risk",
            "Financial Risk",
            "Third-party Risk",
            "Business Continuity",
            "Crisis Management",
            "Ethics & Governance",
            "Data Privacy",
            "Insurance & Risk Transfer",
            "Fraud Prevention",
            "Policy Development",
            "Risk Monitoring",
            "Audit Committee",
            "Legal Compliance",
            "Environmental Risk",
            "Health & Safety",
            "Vendor Compliance",
            "Contract Risk",
            "Credit Risk",
            "Market Risk",
            "Investment Risk",
            "Reputation Risk",
            "Strategic Risk",
            "Others",

        ],
        "Supply Chain Management": [
            "Procurement Strategy",
            "Supplier Management",
            "Inventory Optimization",
            "Demand Planning",
            "Logistics Optimization",
            "Warehouse Management",
            "Distribution Network",
            "Transportation Management",
            "Reverse Logistics",
            "Supply Chain Visibility",
            "Sourcing & Contracting",
            "Supplier Collaboration",
            "Risk & Resilience",
            "Sustainability in Supply Chain",
            "Cost Management",
            "Operational Efficiency",
            "Technology Enablement",
            "Analytics & Reporting",
            "Compliance & Audit",
            "Supplier Diversity",
            "Inventory Accuracy",
            "Order Fulfillment",
            "Packaging Optimization",
            "Capacity Planning",
            "Continuous Improvement",
            "Others",

        ],
        "Product & R&D": [
            "Product Development",
            "R&D Strategy",
            "Design Thinking",
            "Prototyping",
            "Testing & QA",
            "Innovation Labs",
            "Product Roadmap",
            "Technology Scouting",
            "Market Research",
            "Customer Co-creation",
            "Product Portfolio",
            "Product Launch",
            "Agile Development",
            "Sustainability Design",
            "IP Management",
            "Cross-functional Collaboration",
            "Supplier Innovation",
            "Time-to-Market Optimization",
            "Product Analytics",
            "Idea Management",
            "Process Optimization",
            "Lifecycle Management",
            "Continuous Improvement",
            "Global Collaboration",
            "Product Governance",
            "Others",

        ],
        "Leadership & Talent": [
            "Executive Development",
            "Succession Planning",
            "Performance Management",
            "Coaching & Mentoring",
            "Leadership Competency",
            "High Potential Programs",
            "Organizational Design",
            "Change Leadership",
            "Team Leadership",
            "Strategic Thinking",
            "Decision Making",
            "Communication & Influence",
            "Employee Engagement Leadership",
            "Conflict Resolution",
            "Cross-cultural Leadership",
            "Ethical Leadership",
            "Innovation Leadership",
            "Talent Analytics",
            "Management Training",
            "Executive Coaching",
            "Leadership Metrics",
            "Global Leadership",
            "Collaboration & Networking",
            "Leadership Assessment",
            "Leadership Pipeline",
            "Others",

        ],
        "IT & Technology": [
            "Infrastructure Management",
            "Cloud Computing",
            "Cybersecurity",
            "Data Analytics",
            "ERP Systems",
            "CRM Systems",
            "Network Management",
            "Application Development",
            "DevOps Practices",
            "IT Governance",
            "Digital Workplace",
            "Business Intelligence",
            "AI & ML",
            "IT Service Management",
            "Database Management",
            "System Integration",
            "IoT Enablement",
            "Collaboration Tools",
            "Technology Innovation",
            "IT Risk Management",
            "IT Compliance",
            "Cost Optimization",
            "IT Project Management",
            "IT Training & Skills",
            "Technology Roadmap",
            "Others",

        ],
        "Sustainability & ESG": [
            "Environmental Sustainability",
            "Social Responsibility",
            "Governance & Ethics",
            "Energy Management",
            "Waste & Recycling",
            "Water Management",
            "Carbon Emission Reduction",
            "Sustainable Sourcing",
            "Community Engagement",
            "Health & Safety",
            "Diversity & Inclusion",
            "ESG Reporting",
            "Sustainable Products",
            "Climate Risk Management",
            "Employee Wellbeing",
            "Green Buildings",
            "Renewable Energy",
            "Circular Economy",
            "Stakeholder Engagement",
            "Ethical Business Practices",
            "Compliance & Risk",
            "Innovation for Sustainability",
            "Sustainable Logistics",
            "Training & Awareness",
            "CSR Programs",
            "Others",
        ],
    }

    @classmethod
    def get_initiative_focus_area_choices(cls):
        return [(p, p) for p in cls.INITIATIVE_HIERARCHY.keys()]

    @classmethod
    def get_area_choices(cls, initiative_focus_area):
        return [(a, a) for a in cls.INITIATIVE_HIERARCHY.get(initiative_focus_area, [])]