#
#
class SwotChoicesService:
    """
    Production-level SWOT hierarchy with detailed categories:
    - Strength & Weakness: use organizational pillars/focus areas
    - Opportunity & Threat: use PESTEL dimensions
    - Language aligned to SWOT terminology
    """

    SWOT_HIERARCHY = {
        "Strength": {
            "Resources & Capabilities": [
                "Strong brand reputation",
                "Skilled and experienced workforce",
                "Robust financial position",
                "Patented and proprietary technologies",
                "Efficient supply chain",
                "Advanced R&D capabilities",
                "Access to strategic partnerships",
                "Global operational presence",
                "Well-maintained production facilities",
                "High employee expertise and knowledge",
            ],
            "Operational Excellence": [
                "High-quality standards and certifications",
                "Lean and scalable operations",
                "Efficient logistics and distribution",
                "Robust risk management processes",
                "Continuous improvement culture",
                "Strong performance metrics and KPIs",
                "Quick response to market demand",
                "Low operational downtime",
                "Automated production and digital processes",
                "Effective resource allocation",
            ],
            "Human Capital & Culture": [
                "High employee engagement",
                "Strong corporate culture",
                "Effective leadership development",
                "Low turnover and absenteeism",
                "Innovative thinking culture",
                "Diverse and inclusive workforce",
                "Mentorship and training programs",
                "Collaboration and teamwork",
                "Employee recognition programs",
                "Talent retention strategies",
            ],
            "Technology & Digital Enablement": [
                "Advanced IT and cybersecurity infrastructure",
                "Cloud adoption and ERP integration",
                "AI and automation-enabled operations",
                "Data-driven decision-making capabilities",
                "Digital product portfolio",
                "Mobile and IoT technologies",
                "Big data and analytics capabilities",
                "Innovation labs and digital R&D",
                "Rapid prototyping and testing",
                "Digital transformation readiness",
            ],
            "Customer & Market Orientation": [
                "High customer loyalty and retention",
                "Strong brand recognition and reputation",
                "Diverse customer segments",
                "Market leadership and competitive advantage",
                "Effective marketing and sales channels",
                "Robust distribution network",
                "Strong partnerships and alliances",
                "Premium pricing power",
                "Customer-centric product development",
                "High Net Promoter Score (NPS)",
            ],
        },
        "Weakness": {
            "Resources & Capabilities": [
                "Over-reliance on limited suppliers",
                "Aging infrastructure",
                "Limited production capacity",
                "Weak intellectual property portfolio",
                "Inadequate R&D investment",
                "Limited financial flexibility",
                "Underdeveloped partnerships",
                "Skill gaps in key workforce areas",
                "Low global market experience",
                "Weak brand visibility",
            ],
            "Operational Challenges": [
                "Inefficient processes and workflows",
                "Poor cross-functional communication",
                "High operational costs",
                "Quality control inconsistencies",
                "Supply chain vulnerabilities",
                "Inventory mismanagement",
                "Slow response to market changes",
                "Low process automation",
                "Maintenance and downtime issues",
                "Inadequate performance monitoring",
            ],
            "Human Capital Gaps": [
                "Low employee engagement",
                "High turnover and absenteeism",
                "Insufficient leadership development",
                "Limited training and skill-building programs",
                "Cultural misalignment",
                "Resistance to change",
                "Weak collaboration among teams",
                "Ineffective succession planning",
                "Innovation culture underdeveloped",
                "Inadequate employee recognition programs",
            ],
            "Technology & Digital Gaps": [
                "Outdated IT infrastructure",
                "Cybersecurity vulnerabilities",
                "Limited digital adoption",
                "Slow AI and automation integration",
                "Data silos and poor analytics",
                "Low cloud and ERP utilization",
                "Lagging digital product offerings",
                "Underdeveloped IoT capabilities",
                "Legacy systems dependencies",
                "Ineffective digital strategy",
            ],
            "Customer & Market Gaps": [
                "Weak brand recognition",
                "Limited product portfolio",
                "Poor market positioning",
                "Ineffective marketing campaigns",
                "Limited customer engagement",
                "Low online presence",
                "Customer dissatisfaction complaints",
                "Slow adaptation to trends",
                "Limited geographic reach",
                "Ineffective feedback mechanisms",
            ],
        },
        "Opportunity": {
            "Political": [
                "Government incentives for innovation",
                "Favorable trade agreements",
                "Deregulation of key markets",
                "Public-private partnership initiatives",
                "Infrastructure investment programs",
                "Policy support for strategic growth",
                "Export subsidies and incentives",
                "Regulatory simplifications",
                "Legal support for IP protections",
                "Local government collaborations",
            ],
            "Economic": [
                "Expansion into emerging markets",
                "Rising disposable incomes",
                "Access to growth capital",
                "Favorable interest rates",
                "Diversification of revenue streams",
                "Increasing consumer spending",
                "Growth in digital economy",
                "Export market opportunities",
                "Strategic acquisitions and partnerships",
                "Economic recovery or growth trends",
            ],
            "Social": [
                "Shifting consumer preferences",
                "Health and wellness trends",
                "Sustainability awareness",
                "Demographic changes favoring growth",
                "Remote work adoption opportunities",
                "Urbanization and lifestyle shifts",
                "Education and skills improvements",
                "Consumer personalization demand",
                "Social media engagement growth",
                "Cultural acceptance of new technologies",
            ],
            "Technological": [
                "AI and machine learning adoption",
                "IoT technology integration",
                "Blockchain and distributed ledger adoption",
                "Automation and robotics opportunities",
                "Cloud computing expansion",
                "Big data analytics",
                "AR/VR technology integration",
                "5G network adoption",
                "Digital platform development",
                "Emerging technology innovation",
            ],
            "Environmental": [
                "Green technology adoption",
                "Sustainable resource utilization",
                "Renewable energy projects",
                "Waste reduction initiatives",
                "Eco-friendly product demand",
                "Environmental certifications",
                "Climate change mitigation programs",
                "Energy efficiency initiatives",
                "CSR sustainability programs",
                "Carbon credit opportunities",
            ],
            "Legal": [
                "Favorable patent laws",
                "Compliance advantage",
                "Regulatory frameworks supporting growth",
                "Industry-specific legislation",
                "Consumer protection alignment",
                "Contract law improvements",
                "Labor law benefits",
                "Environmental law incentives",
                "IP protection enhancements",
                "Legal frameworks for strategic partnerships",
            ],
        },
        "Threat": {
            "Political": [
                "Political instability or unrest",
                "Policy uncertainty",
                "Trade wars and tariffs",
                "Government corruption",
                "Regulatory reversals",
                "Public protests impacting operations",
                "Geopolitical conflicts",
                "Taxation changes",
                "Policy instability",
                "International sanctions",
            ],
            "Economic": [
                "Economic downturn or recession",
                "Currency volatility",
                "Inflation increases",
                "Rising interest rates",
                "Market saturation",
                "Funding constraints",
                "Low consumer spending",
                "Credit shortages",
                "Recession risks",
                "Economic instability in key markets",
            ],
            "Social": [
                "Negative shifts in consumer behavior",
                "Brand perception damage",
                "Employee dissatisfaction",
                "Labor unrest",
                "Consumer activism",
                "Demographic shifts reducing demand",
                "Public health crises",
                "Social media backlash",
                "Cultural resistance",
                "Changing lifestyle trends",
            ],
            "Technological": [
                "Rapid technological obsolescence",
                "Cybersecurity breaches",
                "Digital disruption",
                "High adoption costs",
                "Automation replacing jobs",
                "Intellectual property theft",
                "System failures",
                "Platform dependency risks",
                "Slow technology adoption",
                "Technology skill gaps",
            ],
            "Environmental": [
                "Climate change impacts",
                "Natural disasters",
                "Resource scarcity",
                "Energy price volatility",
                "Environmental regulations",
                "Waste and pollution risks",
                "Sustainability compliance challenges",
                "Extreme weather events",
                "Supply chain interruptions",
                "Environmental lawsuits",
            ],
            "Legal": [
                "Regulatory changes impacting operations",
                "Litigation risks",
                "Labor law changes",
                "Tax law changes",
                "Patent disputes",
                "Contract enforcement issues",
                "Compliance violations",
                "Data privacy regulations",
                "Intellectual property disputes",
                "Industry-specific legal challenges",
            ],
        },
    }

    # Form getters
    @classmethod
    def get_swot_type_choices(cls):
        return [(s, s) for s in cls.SWOT_HIERARCHY.keys()]

    @classmethod
    def get_pillar_choices(cls, swot_type):
        return [(p, p) for p in cls.SWOT_HIERARCHY.get(swot_type, {}).keys()]

    @classmethod
    def get_factor_choices(cls, swot_type, pillar):
        return [(f, f) for f in cls.SWOT_HIERARCHY.get(swot_type, {}).get(pillar, [])]

#