from management_project.models import Vision, OrganizationalProfile


class VisionService:


    SECTOR_VISION_MAP = {
        'education': [
            "To create a world where every mind has access to learning",
            "To empower lifelong learners with innovative tools",
            "To foster curiosity, creativity, and critical thinking in all students",
            "To make education inclusive for all children and adults",
            "To inspire communities to value knowledge and growth",
            "To bridge digital divides and expand learning opportunities",
            "To cultivate leaders for a better tomorrow",
            "To strengthen teaching excellence worldwide",
            "To integrate technology seamlessly into learning",
            "To transform classrooms into hubs of innovation",
            "To unlock potential in underserved regions",
            "To create equitable pathways to success",
            "To encourage collaboration across educational institutions",
            "To nurture talent and lifelong skills",
            "To promote sustainability and resilience in education",
            "To advance global research and knowledge sharing",
            "To foster adaptive learning for future challenges",
            "To create meaningful and engaging learning experiences",
            "To inspire ethical and responsible citizenship",
            "To innovate continuously for educational excellence"
        ],

        'healthcare': [
            "To ensure health and well-being for every individual",
            "To make quality healthcare accessible for all",
            "To empower communities with preventive care knowledge",
            "To leverage technology for better patient outcomes",
            "To reduce disparities in health access globally",
            "To advance medical research for innovative treatments",
            "To build resilient health systems for the future",
            "To prioritize mental health and emotional wellness",
            "To integrate digital health solutions seamlessly",
            "To create patient-centered healthcare experiences",
            "To improve global vaccination and disease prevention",
            "To foster collaboration across healthcare providers",
            "To enhance emergency and trauma response systems",
            "To reduce costs without compromising quality",
            "To innovate for sustainable healthcare solutions",
            "To promote public health education widely",
            "To empower healthcare professionals continuously",
            "To adopt data-driven decision making in medicine",
            "To ensure safe and reliable medical services",
            "To inspire healthy lifestyles in communities"
        ],

        'information_technology': [
            "To connect the world through innovative technology",
            "To empower businesses with digital transformation",
            "To enable smarter decision-making with data insights",
            "To provide secure and reliable IT solutions",
            "To foster creativity and innovation through technology",
            "To make technology accessible for every organization",
            "To integrate AI and automation for efficiency",
            "To support cloud-first and SaaS adoption globally",
            "To optimize IT operations through analytics",
            "To protect digital assets with advanced cybersecurity",
            "To inspire continuous learning in tech communities",
            "To enhance user experiences through design and innovation",
            "To accelerate growth with scalable IT solutions",
            "To drive industry standards with cutting-edge tech",
            "To foster collaboration across global IT ecosystems",
            "To make complex systems simple and efficient",
            "To integrate emerging technologies responsibly",
            "To support sustainable and green IT practices",
            "To enable remote and hybrid work with ease",
            "To unlock business potential through technology"
        ],

        'finance_banking': [
            "To empower individuals and businesses financially",
            "To make banking simple, transparent, and accessible",
            "To innovate financial solutions for every need",
            "To promote responsible investment and wealth creation",
            "To provide security and trust in all transactions",
            "To expand financial literacy for all communities",
            "To foster global economic collaboration",
            "To leverage technology for seamless payments",
            "To optimize financial operations with data insights",
            "To ensure sustainability and ethical finance practices",
            "To support entrepreneurs and small businesses",
            "To enhance risk management through innovation",
            "To enable inclusive and equitable financial services",
            "To adopt AI and automation for smarter banking",
            "To drive digital transformation across finance",
            "To encourage transparency and accountability",
            "To reduce barriers to global financial access",
            "To create scalable and adaptive banking solutions",
            "To inspire trust and confidence in financial institutions",
            "To lead with integrity in the global financial ecosystem"
        ],

        'agriculture': [
            "To nourish the world with sustainable farming practices",
            "To empower farmers with modern technology and knowledge",
            "To promote food security and equitable access",
            "To integrate digital solutions in agriculture",
            "To foster innovation in crop and livestock management",
            "To advance sustainable and climate-resilient farming",
            "To improve supply chains from farm to fork",
            "To support local communities and agribusinesses",
            "To implement precision agriculture and data analytics",
            "To adopt environmentally friendly farming practices",
            "To create opportunities for smallholder farmers",
            "To expand global access to quality agricultural products",
            "To innovate for efficiency and sustainability",
            "To reduce waste and maximize yields",
            "To promote research in agritech and biotechnology",
            "To strengthen rural economies and livelihoods",
            "To integrate renewable energy in agriculture",
            "To inspire collaboration across the food ecosystem",
            "To foster resilience against climate challenges",
            "To lead with vision for a sustainable future"
        ],

        'manufacturing': [
            "To design and deliver quality products efficiently",
            "To adopt sustainable manufacturing practices",
            "To innovate in automation and production technology",
            "To ensure safety and compliance in operations",
            "To optimize supply chains globally",
            "To enhance productivity through lean manufacturing",
            "To empower workforce skills and development",
            "To implement data-driven production decisions",
            "To minimize waste and improve resource efficiency",
            "To foster continuous improvement in processes",
            "To collaborate with partners for innovation",
            "To advance circular economy initiatives",
            "To integrate smart factories and IoT",
            "To improve product quality and reliability",
            "To invest in research and development",
            "To expand markets responsibly and sustainably",
            "To maintain ethical labor practices",
            "To enhance product customization capabilities",
            "To adopt flexible and scalable production methods",
            "To lead the industry in innovation and sustainability"
        ],

        'energy_utilities': [
            "To provide reliable and sustainable energy solutions",
            "To reduce environmental impact of energy production",
            "To integrate renewable energy sources",
            "To optimize energy efficiency across networks",
            "To innovate smart grid technologies",
            "To empower communities with clean energy access",
            "To ensure safety and regulatory compliance",
            "To promote responsible consumption and conservation",
            "To advance energy storage solutions",
            "To leverage technology for energy management",
            "To support sustainable industrial energy use",
            "To foster collaboration across energy sectors",
            "To invest in research for future energy solutions",
            "To implement digital monitoring and analytics",
            "To reduce carbon footprint globally",
            "To enhance customer engagement and awareness",
            "To adopt circular economy principles in utilities",
            "To provide affordable energy access",
            "To prepare for climate resilience and adaptation",
            "To inspire innovation for a sustainable energy future"
        ],

        'environment_sustainability': [
            "To protect ecosystems and biodiversity",
            "To promote sustainable development globally",
            "To reduce carbon emissions and environmental impact",
            "To encourage renewable energy adoption",
            "To integrate circular economy principles",
            "To foster environmental awareness in communities",
            "To innovate for sustainable products and services",
            "To preserve natural resources for future generations",
            "To support climate resilience initiatives",
            "To implement green technologies across sectors",
            "To collaborate with governments for sustainability",
            "To advance sustainable urban planning",
            "To reduce waste and improve recycling systems",
            "To monitor and mitigate environmental risks",
            "To empower organizations with ESG strategies",
            "To educate and inspire behavioral change",
            "To adopt sustainable supply chain practices",
            "To protect water, air, and soil quality",
            "To foster global cooperation for the environment",
            "To lead with vision for a green future"
        ],

        'transport_logistics': [
            "To deliver goods and people efficiently and safely",
            "To optimize global supply chains with technology",
            "To reduce environmental impact in transportation",
            "To integrate intelligent traffic and logistics systems",
            "To ensure reliability and punctuality in services",
            "To foster innovation in mobility solutions",
            "To enhance customer experience in transport",
            "To adopt sustainable fuels and energy sources",
            "To improve infrastructure and connectivity",
            "To promote safe and ethical transport operations",
            "To leverage data for logistics optimization",
            "To support urban mobility solutions",
            "To implement smart fleet management",
            "To enhance regulatory compliance",
            "To drive digital transformation in transport",
            "To expand access to transportation for communities",
            "To improve cargo tracking and transparency",
            "To reduce waste in supply chain management",
            "To empower workforce with skills and training",
            "To lead innovation in global mobility systems"
        ],

        'tourism_hospitality': [
            "To create memorable experiences for travelers",
            "To promote sustainable tourism practices",
            "To foster cultural appreciation and exchange",
            "To innovate in hospitality services globally",
            "To ensure safety and comfort for guests",
            "To integrate technology in travel planning",
            "To enhance accessibility for all travelers",
            "To support local communities through tourism",
            "To improve service quality and consistency",
            "To implement environmentally responsible operations",
            "To leverage data for customer insights",
            "To train and empower hospitality workforce",
            "To drive growth in sustainable travel",
            "To offer inclusive and diverse experiences",
            "To promote wellness and leisure activities",
            "To foster collaboration across travel networks",
            "To enhance infrastructure for tourism",
            "To encourage responsible travel behavior",
            "To create scalable hospitality solutions",
            "To lead innovation in the global tourism industry"
        ],

        'construction_real_estate': [
            "To build sustainable and resilient infrastructure",
            "To design innovative living and working spaces",
            "To promote safety and compliance in construction",
            "To integrate green building practices",
            "To optimize resource efficiency in projects",
            "To enhance urban development through smart design",
            "To deliver high-quality projects on time and budget",
            "To foster collaboration with communities",
            "To adopt digital solutions for project management",
            "To implement energy-efficient building systems",
            "To advance modular and prefabricated construction",
            "To improve accessibility in buildings and spaces",
            "To ensure durability and long-term value",
            "To embrace circular economy principles",
            "To innovate in sustainable materials and methods",
            "To promote affordable housing initiatives",
            "To leverage data for construction efficiency",
            "To inspire design excellence and aesthetics",
            "To integrate smart technologies in properties",
            "To lead in sustainable real estate development"
        ],

        'telecommunications': [
            "To connect people globally with reliable networks",
            "To provide high-speed and secure communications",
            "To innovate in mobile and broadband technologies",
            "To expand digital access for underserved areas",
            "To enhance customer experiences through technology",
            "To integrate IoT and smart devices seamlessly",
            "To drive innovation in 5G and future networks",
            "To ensure regulatory compliance and safety",
            "To adopt energy-efficient network solutions",
            "To foster global collaboration across operators",
            "To provide scalable infrastructure for growth",
            "To leverage analytics for service optimization",
            "To improve digital literacy and accessibility",
            "To enable seamless connectivity for businesses",
            "To implement AI-driven network management",
            "To expand services to rural and remote regions",
            "To lead in telecommunications innovation",
            "To prioritize security and privacy in communications",
            "To support emergency and disaster communications",
            "To enable inclusive digital economies worldwide"
        ],

        'research_development': [
            "To advance knowledge and scientific discovery",
            "To foster innovation across industries",
            "To support collaborative research initiatives",
            "To integrate technology in research methods",
            "To translate research into practical solutions",
            "To invest in talent and capacity building",
            "To ensure ethical and responsible research",
            "To promote data-driven decision making",
            "To improve global access to research outputs",
            "To enable innovation ecosystems for growth",
            "To adopt sustainable research practices",
            "To drive breakthroughs in science and technology",
            "To enhance cross-disciplinary collaboration",
            "To create scalable solutions for real-world challenges",
            "To strengthen intellectual property management",
            "To leverage AI and analytics in research",
            "To foster entrepreneurship from research outcomes",
            "To inspire curiosity and problem-solving globally",
            "To advance open science and knowledge sharing",
            "To lead in innovation for societal impact"
        ],

        'public_sector': [
            "To ensure transparent and accountable governance",
            "To provide accessible public services for all",
            "To foster citizen engagement and participation",
            "To implement efficient digital government solutions",
            "To promote social equity and inclusion",
            "To strengthen policy planning and execution",
            "To enhance public sector workforce capability",
            "To adopt evidence-based decision-making",
            "To ensure sustainability in public initiatives",
            "To optimize resource allocation for impact",
            "To innovate for better service delivery",
            "To improve regulatory frameworks and compliance",
            "To empower communities through public programs",
            "To integrate technology for smart governance",
            "To build resilient infrastructure for public services",
            "To foster collaboration across agencies",
            "To enhance transparency through open data",
            "To implement performance measurement systems",
            "To deliver value-driven public outcomes",
            "To lead innovation in public administration"
        ],

        'creative_media': [
            "To inspire creativity across all forms of media",
            "To engage audiences with meaningful content",
            "To promote cultural diversity and inclusion",
            "To innovate in digital and traditional media",
            "To support emerging artists and creators",
            "To leverage technology for content delivery",
            "To foster storytelling that drives impact",
            "To ensure high-quality production standards",
            "To create immersive and interactive experiences",
            "To expand global reach of creative works",
            "To protect intellectual property and rights",
            "To adopt sustainable media practices",
            "To encourage collaboration across creative industries",
            "To implement data-driven audience insights",
            "To promote ethical content creation",
            "To inspire learning through creative expression",
            "To innovate in marketing and brand storytelling",
            "To integrate new media technologies effectively",
            "To enhance engagement and participation",
            "To lead in creativity and cultural impact"
        ],

        'retail_wholesale': [
            "To provide seamless shopping experiences",
            "To optimize supply chain efficiency",
            "To promote sustainable sourcing and products",
            "To leverage data for customer insights",
            "To enhance brand loyalty and satisfaction",
            "To innovate in retail technology and e-commerce",
            "To ensure product quality and safety",
            "To support local businesses and communities",
            "To integrate omnichannel shopping solutions",
            "To drive growth through analytics and trends",
            "To improve logistics and delivery efficiency",
            "To adopt ethical and responsible business practices",
            "To expand access to essential goods",
            "To enhance employee training and engagement",
            "To innovate in retail marketing and experiences",
            "To foster collaboration across supply chains",
            "To anticipate market trends and customer needs",
            "To implement sustainable packaging solutions",
            "To enhance digital and in-store presence",
            "To lead in customer-centric retail strategies"
        ],

        'ecommerce': [
            "To connect buyers and sellers globally",
            "To provide secure and seamless transactions",
            "To deliver exceptional online shopping experiences",
            "To leverage AI for personalized recommendations",
            "To innovate in digital marketing and engagement",
            "To optimize logistics and delivery networks",
            "To support small and medium businesses online",
            "To expand access to global marketplaces",
            "To ensure product authenticity and quality",
            "To foster trust through transparency",
            "To adopt sustainable e-commerce practices",
            "To integrate mobile-first and omnichannel solutions",
            "To enhance customer service and support",
            "To drive data-driven business decisions",
            "To implement scalable technology solutions",
            "To improve conversion rates through insights",
            "To encourage responsible digital consumption",
            "To empower consumers with information",
            "To innovate in cross-border e-commerce",
            "To lead the digital marketplace with integrity"
        ],

        'professional_services': [
            "To deliver excellence in advisory and consulting",
            "To provide innovative solutions for clients",
            "To ensure trust, integrity, and professionalism",
            "To foster talent development and continuous learning",
            "To leverage technology for efficient services",
            "To optimize client outcomes through data insights",
            "To drive sustainable and ethical business practices",
            "To expand global reach and collaboration",
            "To enhance client satisfaction and loyalty",
            "To innovate in service delivery and methodology",
            "To create value for all stakeholders",
            "To implement scalable professional solutions",
            "To maintain compliance and regulatory standards",
            "To empower organizations with actionable insights",
            "To adapt to changing market dynamics",
            "To promote thought leadership and research",
            "To build resilient and adaptive teams",
            "To foster collaboration across industries",
            "To inspire innovation in professional services",
            "To lead with vision and strategic impact"
        ],

        'hospitality_food': [
            "To delight guests with exceptional experiences",
            "To provide safe, healthy, and sustainable food",
            "To innovate in hospitality and dining services",
            "To integrate technology for efficiency and personalization",
            "To promote cultural appreciation through cuisine",
            "To support local communities and suppliers",
            "To enhance staff training and professional development",
            "To ensure consistent quality and service excellence",
            "To adopt eco-friendly and sustainable operations",
            "To foster memorable customer experiences",
            "To expand access to diverse culinary offerings",
            "To improve supply chain and sourcing efficiency",
            "To optimize guest satisfaction and loyalty",
            "To integrate wellness and nutrition trends",
            "To implement scalable and innovative solutions",
            "To lead in hospitality industry standards",
            "To embrace digital engagement and marketing",
            "To foster innovation in menus and experiences",
            "To enhance operational efficiency with technology",
            "To create a welcoming and inclusive environment"
        ],

        'mining_resources': [
            "To extract resources responsibly and sustainably",
            "To innovate in mining technologies and safety",
            "To reduce environmental impact in operations",
            "To ensure ethical and transparent practices",
            "To optimize resource utilization efficiently",
            "To foster workforce safety and skill development",
            "To implement community engagement initiatives",
            "To advance research in resource extraction",
            "To improve supply chain transparency and efficiency",
            "To adopt renewable and low-impact energy solutions",
            "To ensure compliance with environmental regulations",
            "To promote sustainable exploration practices",
            "To invest in rehabilitation and reclamation projects",
            "To integrate data and analytics for decision-making",
            "To reduce carbon footprint across operations",
            "To lead innovation in the mining sector",
            "To empower communities through sustainable initiatives",
            "To maintain operational excellence and reliability",
            "To create value for stakeholders responsibly",
            "To inspire innovation and sustainability globally"
        ],

    }

    def __init__(self, org_obj: OrganizationalProfile):
        self.org = org_obj
        self.sector_name = org_obj.sector_name

    def get_choices(self):
        """Return list of tuples for form select."""
        visions = self.SECTOR_VISION_MAP.get(self.sector_name, [])
        return [(v, v) for v in visions]

    def validate_choice(self, vision_statement):
        if vision_statement not in self.SECTOR_VISION_MAP.get(self.sector_name, []):
            raise ValueError(f"Invalid vision '{vision_statement}' for sector '{self.sector_name}'.")

    def create_vision(self, vision_statement):
        self.validate_choice(vision_statement)
        return Vision.objects.create(organization_name=self.org, vision_statement=vision_statement)
